apiVersion: v1
kind: ReplicationController
metadata:
  name: vertex-rc
spec:
  replicas: 3
  selector:
    app: myvertexpod
    version: 2.6.2
  template:
    metadata:
      labels:
        app: myvertexpod
        version: 2.6.2
    spec:
      containers:
        - name: myvertexapp-container
          image: nginx
          ports:
            - containerPort: 80
